// ═══════════════════════════════════════════════════════
//  THE TOTE BAG COMPANY — PRODUCTS CATALOG
//  ✦ Edit THIS file to add/remove/update any product ✦
//  No need to touch shop.html ever again
// ═══════════════════════════════════════════════════════

const TTBC_PRODUCTS = [

  // ─── HOW TO ADD A NEW PRODUCT ───────────────────────
  // Copy any block below, paste at the end of the array
  // (before the last ]; )
  // Fill in your details, save — it shows up automatically
  // ────────────────────────────────────────────────────

  {
    id: "ttbc-001",
    name: "Running Late But Mentally in Cubbon Park",
    shortName: "Cubbon Park Tote",          // shown on small cards
    price: 699,
    mrp: 899,                               // strike-through price (set same as price for no discount)
    badge: "popular",                       // "new" | "popular" | "limited" | "collab" | "coming" | ""
    badgeText: "Fan Fav",
    tags: ["bengaluru"],                    // used for filters — pick from: bengaluru, worklife, classic, limited
    inStock: true,
    quantity: 12,
    canvasColor: "#F2EDE0",                 // hex for the bag preview
    threadColor: "#4A7C8E",
    canvasLabel: "Cream canvas",
    threadLabel: "Teal thread",
    line1: "Running late but",              // text lines on bag (max 3 lines)
    line2: "mentally in",
    line3: "Cubbon Park",
    line3Color: "#4A7C8E",                  // accent color for line3
    shopifyUrl: "",                         // paste your Shopify product URL here when ready
    shopifyVariantId: "",                   // paste variant ID from Shopify for API cart
  },

  {
    id: "ttbc-002",
    name: "Booked Cab. Cancelled. Booked Again.",
    shortName: "Booked Cab Tote",
    price: 649,
    mrp: 799,
    badge: "new",
    badgeText: "New",
    tags: ["bengaluru"],
    inStock: true,
    quantity: 8,
    canvasColor: "#D4C9B0",
    threadColor: "#3D1F0D",
    canvasLabel: "Sand canvas",
    threadLabel: "Brown thread",
    line1: "Booked cab.",
    line2: "Cancelled.",
    line3: "Booked again.",
    line3Color: "#3D1F0D",
    shopifyUrl: "",
    shopifyVariantId: "",
  },

  {
    id: "ttbc-003",
    name: "Surviving on Filter Coffee & Delusion",
    shortName: "Filter Coffee Tote",
    price: 749,
    mrp: 999,
    badge: "popular",
    badgeText: "Fan Fav",
    tags: ["bengaluru", "worklife"],
    inStock: true,
    quantity: 15,
    canvasColor: "#7B3F1A",
    threadColor: "#C9973A",
    canvasLabel: "Coffee brown canvas",
    threadLabel: "Gold thread",
    line1: "Surviving on",
    line2: "Filter Coffee",
    line3: "& Delusion",
    line3Color: "#C9973A",
    shopifyUrl: "",
    shopifyVariantId: "",
  },

  {
    id: "ttbc-004",
    name: "Metro > Men",
    shortName: "Metro > Men",
    price: 599,
    mrp: 749,
    badge: "limited",
    badgeText: "Limited",
    tags: ["bengaluru"],
    inStock: true,
    quantity: 6,
    canvasColor: "#4A7C8E",
    threadColor: "#F2EDE0",
    canvasLabel: "Teal canvas",
    threadLabel: "Cream thread",
    line1: "Metro",
    line2: "> Men",
    line3: "✦ Namma Metro ✦",
    line3Color: "#C9973A",
    shopifyUrl: "",
    shopifyVariantId: "",
  },

  {
    id: "ttbc-005",
    name: "Namma Traffic Made Me Hot",
    shortName: "Traffic Tote",
    price: 699,
    mrp: 899,
    badge: "new",
    badgeText: "Hot Drop",
    tags: ["bengaluru"],
    inStock: true,
    quantity: 10,
    canvasColor: "#C46A3C",
    threadColor: "#FFFFFF",
    canvasLabel: "Terracotta canvas",
    threadLabel: "White thread",
    line1: "Namma Traffic",
    line2: "Made Me",
    line3: "HOT 🔥",
    line3Color: "#F2EDE0",
    shopifyUrl: "",
    shopifyVariantId: "",
  },

  {
    id: "ttbc-006",
    name: "The OG Classic",
    shortName: "The OG Classic",
    price: 499,
    mrp: 649,
    badge: "popular",
    badgeText: "Classic",
    tags: ["classic"],
    inStock: true,
    quantity: 20,
    canvasColor: "#F2EDE0",
    threadColor: "#3D1F0D",
    canvasLabel: "Raw cream canvas",
    threadLabel: "Brown thread",
    line1: "THE TOTE",
    line2: "BAG CO.",
    line3: "✦ EST. 2025 ✦",
    line3Color: "#C9973A",
    shopifyUrl: "",
    shopifyVariantId: "",
  },

  {
    id: "ttbc-007",
    name: "Burnout Is Real. Carry It Anyway.",
    shortName: "Burnout Tote",
    price: 749,
    mrp: 999,
    badge: "new",
    badgeText: "New",
    tags: ["worklife"],
    inStock: true,
    quantity: 9,
    canvasColor: "#0D0D0D",
    threadColor: "#F2EDE0",
    canvasLabel: "Midnight black canvas",
    threadLabel: "Cream thread",
    line1: "Burnout Is",
    line2: "REAL.",
    line3: "Carry it anyway.",
    line3Color: "#C46A3C",
    shopifyUrl: "",
    shopifyVariantId: "",
  },

  {
    id: "ttbc-008",
    name: "Out of Office. Out of Mind. Out of F***s.",
    shortName: "OOO Tote",
    price: 699,
    mrp: 849,
    badge: "",
    badgeText: "",
    tags: ["worklife"],
    inStock: true,
    quantity: 7,
    canvasColor: "#5A6B3A",
    threadColor: "#F2EDE0",
    canvasLabel: "Olive green canvas",
    threadLabel: "Cream thread",
    line1: "Out of Office.",
    line2: "Out of Mind.",
    line3: "Out of F***s.",
    line3Color: "#C9973A",
    shopifyUrl: "",
    shopifyVariantId: "",
  },

  {
    id: "ttbc-009",
    name: "Your Dream. Your Carry.",
    shortName: "Quit Notice Tote",
    price: 799,
    mrp: 999,
    badge: "limited",
    badgeText: "Limited",
    tags: ["classic", "limited"],
    inStock: true,
    quantity: 5,
    canvasColor: "#C46A3C",
    threadColor: "#FFFFFF",
    canvasLabel: "Terracotta canvas",
    threadLabel: "White thread",
    line1: "Your Dream.",
    line2: "Your Carry.",
    line3: "✦ QUIT NOTICE ✦",
    line3Color: "rgba(255,255,255,0.6)",
    shopifyUrl: "",
    shopifyVariantId: "",
  },

  {
    id: "ttbc-010",
    name: "Not a Morning Person But Here We Are",
    shortName: "Morning Person Tote",
    price: 549,
    mrp: 699,
    badge: "new",
    badgeText: "New",
    tags: ["bengaluru", "worklife"],
    inStock: true,
    quantity: 11,
    canvasColor: "#F2EDE0",
    threadColor: "#C46A3C",
    canvasLabel: "Cream canvas",
    threadLabel: "Terracotta thread",
    line1: "Not a morning",
    line2: "person but",
    line3: "here we are.",
    line3Color: "#C46A3C",
    shopifyUrl: "",
    shopifyVariantId: "",
  },

  {
    id: "ttbc-011",
    name: "Swiggy Instamart Is My Love Language",
    shortName: "Swiggy Love Tote",
    price: 599,
    mrp: 749,
    badge: "",
    badgeText: "",
    tags: ["bengaluru"],
    inStock: true,
    quantity: 14,
    canvasColor: "#4A7C8E",
    threadColor: "#FFFFFF",
    canvasLabel: "Teal canvas",
    threadLabel: "White thread",
    line1: "Swiggy Instamart",
    line2: "Is My Love",
    line3: "Language.",
    line3Color: "#F2EDE0",
    shopifyUrl: "",
    shopifyVariantId: "",
  },

  {
    id: "ttbc-012",
    name: "Main Character. Always.",
    shortName: "Main Character Tote",
    price: 649,
    mrp: 799,
    badge: "popular",
    badgeText: "Bestseller",
    tags: ["worklife", "classic"],
    inStock: true,
    quantity: 18,
    canvasColor: "#3D1F0D",
    threadColor: "#C9973A",
    canvasLabel: "Dark brown canvas",
    threadLabel: "Gold thread",
    line1: "Main",
    line2: "Character.",
    line3: "Always.",
    line3Color: "#C9973A",
    shopifyUrl: "",
    shopifyVariantId: "",
  },

  {
    id: "ttbc-013",
    name: "It's Giving Bengaluru Weather Energy",
    shortName: "BLR Weather Tote",
    price: 549,
    mrp: 699,
    badge: "new",
    badgeText: "New",
    tags: ["bengaluru"],
    inStock: true,
    quantity: 10,
    canvasColor: "#E8E0CE",
    threadColor: "#4A7C8E",
    canvasLabel: "Sand canvas",
    threadLabel: "Teal thread",
    line1: "It's giving",
    line2: "Bengaluru",
    line3: "weather energy",
    line3Color: "#4A7C8E",
    shopifyUrl: "",
    shopifyVariantId: "",
  },

  {
    id: "ttbc-014",
    name: "Do the Work. Take the Bag. Leave.",
    shortName: "Do the Work Tote",
    price: 699,
    mrp: 849,
    badge: "",
    badgeText: "",
    tags: ["worklife"],
    inStock: true,
    quantity: 8,
    canvasColor: "#C9973A",
    threadColor: "#3D1F0D",
    canvasLabel: "Gold canvas",
    threadLabel: "Brown thread",
    line1: "Do the work.",
    line2: "Take the bag.",
    line3: "Leave.",
    line3Color: "#3D1F0D",
    shopifyUrl: "",
    shopifyVariantId: "",
  },

  {
    id: "ttbc-015",
    name: "Soft Life Era 🌱",
    shortName: "Soft Life Tote",
    price: 549,
    mrp: 699,
    badge: "limited",
    badgeText: "Limited",
    tags: ["classic", "limited"],
    inStock: true,
    quantity: 6,
    canvasColor: "#F2EDE0",
    threadColor: "#5A6B3A",
    canvasLabel: "Natural cream canvas",
    threadLabel: "Olive thread",
    line1: "🌱",
    line2: "Soft Life Era.",
    line3: "✦ TTBC ✦",
    line3Color: "#C9973A",
    shopifyUrl: "",
    shopifyVariantId: "",
  },

  // ─── COMING SOON — set inStock: false ───────────────
  {
    id: "ttbc-016",
    name: "Mystery Drop — You Vote, We Stitch",
    shortName: "Mystery Drop",
    price: null,                            // null = shows "???" 
    mrp: null,
    badge: "coming",
    badgeText: "Coming Soon",
    tags: ["limited"],
    inStock: false,
    quantity: 0,
    canvasColor: "#E8E0CE",
    threadColor: "#3D1F0D",
    canvasLabel: "Canvas TBD",
    threadLabel: "Thread TBD",
    line1: "something good",
    line2: "is coming...",
    line3: "",
    line3Color: "#7B3F1A",
    shopifyUrl: "waitlist.html",
    shopifyVariantId: "",
  },

  // ─── ADD YOUR NEXT PRODUCT HERE ─────────────────────
  // {
  //   id: "ttbc-017",
  //   name: "Your New Design Name",
  //   shortName: "Short Name",
  //   price: 599,
  //   mrp: 749,
  //   badge: "new",
  //   badgeText: "New",
  //   tags: ["bengaluru"],
  //   inStock: true,
  //   quantity: 10,
  //   canvasColor: "#F2EDE0",
  //   threadColor: "#3D1F0D",
  //   canvasLabel: "Canvas type",
  //   threadLabel: "Thread color",
  //   line1: "Line one text",
  //   line2: "Line two text",
  //   line3: "Line three text",
  //   line3Color: "#C9973A",
  //   shopifyUrl: "",
  //   shopifyVariantId: "",
  // },

];


// ═══════════════════════════════════════════════════════
//  SHOPIFY CONFIG — fill this in when you have your store
// ═══════════════════════════════════════════════════════

const SHOPIFY_CONFIG = {
  domain: "",                    // e.g. "thetotebagcompany.myshopify.com"
  storefrontToken: "",           // your Storefront API access token
  connected: false,              // flip to true once API is set up
};


// ═══════════════════════════════════════════════════════
//  SITE CONFIG — global settings
// ═══════════════════════════════════════════════════════

const SITE_CONFIG = {
  currency: "₹",
  freeShippingAbove: 999,
  shippingCharge: 80,
  instagramUrl: "https://instagram.com/thetotebagcompany",
  whatsappNumber: "",            // e.g. "919876543210"
  launchDate: "2025-09-01",     // used for countdown if needed
};
